const products = {
	hotDeals: [
		{
			name: "Dell-SE2422H",
			img: 1,
			price: `1399zł`,
			stars: 4,
			opinions: 824,
			productId: 1,
		},
		{
			name: "G4M3R-HERO",
			img: 2,
			price: `8759zł`,
			stars: 5,
			opinions: 147,
			productId: 2,
		},
		{
			name: "Genesis-Xenon-220-G2-RGB",
			img: 3,
			price: `239zł`,
			stars: 3,
			opinions: 923,
			productId: 3,
		},
		{
			name: "Gigabyte-M32QC-Curved-HDR-KVM",
			img: 4,
			price: `1289zł`,
			stars: 4,
			opinions: 517,
			productId: 4,
		},
		{
			name: "LG-Ultrawide-34WP65CP-B",
			img: 5,
			price: `1820zł`,
			stars: 5,
			opinions: 234,
			productId: 5,
		},
		{ name: "Razer-Ornata-V2", img: 6, price: `329zł`, stars: 3, productId: 6 },
		{
			name: "Samsung-Odyssey-C34G55TWWPX",
			img: 7,
			price: `1658zł`,
			stars: 4,
			opinions: 673,
			productId: 7,
		},
		{
			name: "Logitech-G502-HERO",
			img: 8,
			price: `189zł`,
			stars: 4,
			opinions: 114,
			productId: 8,
		},
		{
			name: "Silver-Monkey-X-Mandrill",
			img: 9,
			price: `243zł`,
			stars: 3,
			opinions: 581,
			productId: 9,
		},
		{
			name: "Genesis-Xenon-220-G2-RGB",
			img: 10,
			price: `89zł`,
			stars: 4,
			opinions: 234,
			productId: 10,
		},
		{
			name: "Logitech-G502-HERO",
			img: 8,
			price: `129zł`,
			stars: 4,
			opinions: 734,
			productId: 11,
		},
		{
			name: "Silver-Monkey-X-Mandrill",
			img: 9,
			price: `149zł`,
			stars: 5,
			opinions: 992,
			productId: 12,
		},
		{
			name: "Logitech-G502-HERO",
			img: 8,
			price: `79zł`,
			stars: 3,
			opinions: 683,
			productId: 13,
		},
		{
			name: "Genesis-Xenon-220-G2-RGB",
			img: 10,
			price: `84zł`,
			stars: 5,
			opinions: 223,
			productId: 14,
		},
		{
			name: "Gigabyte-M32QC-Curved-HDR-KVM",
			img: 4,
			price: `899zł`,
			stars: 4,
			opinions: 312,
			productId: 15,
		},
		{
			name: "Silver-Monkey-X-Mandrill",
			img: 9,
			price: `289zł`,
			stars: 4,
			opinions: 782,
			productId: 16,
		},
	],
};

export default products;
